### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by YoriNealle** [ryanhefner/react-scroll-trigger#132]
Using ScrollTrigger with React/Typescript (.tsx file) is causing errors for me in Visual Studio Code.

![image](https://user-images.githubusercontent.com/60892588/76357260-a614cc80-6317-11ea-82e1-9d9c18a2797a.png)

```
import ScrollTrigger from 'react-scroll-trigger';
```
Is how I'm importing it. The code is compiling fine and there are no problems running the actual code, but could this somehow be adressed so I can use ScrollTrigger in a Typescript project?

**Comment by ryanhefner** [comment]
Thanks for letting me know, @YoriNealle. I’ll look into this and see what's up. I also just pushed up a new patch that includes a few dependency updates. Not sure if those would address the issue, but let me know if pulling down the latest resolves it.

In the meantime, I’ll get a project up and running to test with.

**Comment by MaxSpass** [comment]
> Thanks for letting me know, @YoriNealle. I’ll look into this and see what's up. I also just pushed up a new patch that includes a few dependency updates. Not sure if those would address the issue, but let me know if pulling down the latest resolves it.
> 
> In the meantime, I’ll get a project up and running to test with.

**Bug is still relevant.**

"react-scroll-trigger": "^0.6.5",
