### ISSUE TITLE
Not working in Safari?

### ISSUE THREAD

**Issue by theFrawley** [ryanhefner/react-scroll-trigger#40]
Thank you for making such a simple and elegant component. 
Works great in Chrome, but Safari seems to call the onEnter function when the page loads?

**Comment by ryanhefner** [comment]
Thanks! Do you have the `triggerOnLoad` prop set? If not, could you send me a link to review? I can also do some testing and see what's up. I have this on a few production sites and haven’t come across this problem in Safari, but let me go back to a few and check them out.

**Comment by ryanhefner** [comment]
@theFrawley I’m hoping that your silence means that it’s working fine. Going to close this one out, but feel free to reopen it if you are stilling running into issues in Safari. Thanks!
