### ISSUE TITLE
When should onExit and onEnter fire?

### ISSUE THREAD

**Issue by designspin** [ryanhefner/react-scroll-trigger#5]
It appears onExit and onEnter are only triggered at the top of the viewport? Is this expected behaviour?

I need to detect the same at the bottom of the browser!

**Comment by designspin** [comment]
Actually, looks like body height is used in the calc, so setting body, html to 100% is the fix here.

Thanks for your great work.

**Comment by ryanhefner** [comment]
@designspin Oh, great catch! I'll look into making that a little bit more resilient for if that's not set. And, thanks! 🙌
